trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: azurecontainer
              containerRegistry: myACRconnection
              tags: latest

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: Azure gor students
              appName: my-docker-app
              containers: 'myappregistrylab5.azurecr.io/azurecontainer:latest'