trigger:
- master

resources:
- repo: self

variables:
  dockerRegistry: 'myappregistry.azurecr.io'
  imageName: 'my-aspnet-app'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'myACRconnection'
        repository: $(imageName)
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/AzureContainer/Dockerfile'
        tags: |
          $(tag)
          latest  # Дополнительный тег