trigger:
- master  # Гілка, яка запускає пайплайн

variables:
  dockerRegistry: 'myappregistrylab5.azurecr.io'  # Ваш ACR
  imageName: 'azurecontainer'                     # Назва образу
  tag: '$(Build.BuildId)'                         # Тег (можна використовувати 'latest')

stages:
- stage: BuildAndPush
  displayName: Build and Push to ACR
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'myACRconnection'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: $(tag)

- stage: Deploy
  displayName: Deploy to App Service
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy to Azure Web App
      inputs:
        azureSubscription: 'my ACRconnection'  # Service Connection до Azure
        appName: 'my-docker-app'                # Назва вашого App Service
        containers: '$(dockerRegistry)/$(imageName):$(tag)'
